[project]
name = "package-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jens Peder Meldgaard", email = "jpm@halfspace.io" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
package-a = "package_a:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
